[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "glib",
  "dbus",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "libxkbcommon",
  "pango",
  "cairo",
  "expat",
  "fontconfig",
  "alsa-lib"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
NODE_ENV = "production"
