[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run start:all"
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = -1
healthcheckPath = "/health"
healthcheckTimeout = 120
